### ISSUE TITLE
EX: CSR pages for all content types

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1067]
The `cdn_redirect` module can detect requests to pages that should be available, but are not built yet. These are rewritten to a `___csr/[content-type]` template that will load data based on the current path. This way we can have a preview of a new page even before it was build.

- [x] load by path functionality #1149 
- [ ] create a template for each content type that takes the current path and attempts to "live" resolve it
- [x] add logic to `cdn_redirect` that detects that a page that netlify tries to redirect "should" exist, and proxy the types preview template instead (like the current 404 proxy) #1152 
- [x] reduce cache max age for redirect and 404 responses to 5 minutes #1148
