### ISSUE TITLE
Shared package with reusable molecules

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1172]
- [ ] create a new reusable package `@amazeelabs/molecules` that will contain reusable react components
- [ ] use `vite create` to do that. configure it for [library output](https://vitejs.dev/guide/build.html#library-mode)
- [ ] initiate storybook (should detect vite correctly by now)
- [ ] add tailwind for story styling
- [ ] add chromatic tests

Add first common elements that should be shared between projects
- [ ] #715 youtube/vimeo embeds
- [ ] #1171 dropdown / mobile navigation
- [ ] #1173 collapsible element
- [ ] #452 success/warning/error messages
- ... anything else that makes sense

All components should be as unstyled as possible and follow the paradigm of [headless ui](https://headlessui.com/).
